---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: aws-nginx
  namespace: kargo-promo-branch-test
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      semverConstraint: ^1.24.0
