---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-promo-branch-test
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: aws-nginx
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/hiddeco/kargo-promo-branch-test.git
          checkout:
          - branch: main
            path: ./src
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/env/test
          images:
          - image: public.ecr.aws/nginx/nginx
      - uses: git-commit
        as: commit
        config:
          path: ./src
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./src
      - uses: argocd-update
        config:
          apps:
          - name: kargo-promo-branch-test-test
            sources:
            - repoURL: https://github.com/hiddeco/kargo-promo-branch-test.git
              desiredCommitFromStep: commit
