---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-promo-branch-test
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
  template:
    metadata:
      name: kargo-promo-branch-test-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-promo-branch-test:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/hiddeco/kargo-promo-branch-test.git
        path: ./{{stage}}
        targetRevision: env/{{stage}}
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-promo-branch-test-{{stage}}
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - FailOnSharedResource=true
        - CreateNamespace=true
