name: Commit
on:
  push:
    branches:
    - main

jobs:
  render-manifests:
    name: Render manifests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetBranch:
        - env/test
    steps:
    - name: Render and Commit Manifests
      uses: akuity/kargo-render-action@v0.1.0-rc.40
      with:
        personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
        targetBranch: ${{ matrix.targetBranch }}
